---
# Home Assistant Glow
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: home-assistant-glow
  friendly_name: Home Assistant Glow
  project_version: "4.3.0"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - ESP32 Generic - v${project_version}"

  # Define the GPIO pins  
  pulse_pin1: GPIO33  # Has internal pullup capability
  pulse_pin2: GPIO32  # Has internal pullup capability
  status_led: GPIO5
  led_pin_red: GPIO2   # Moved to GPIO2
  led_pin_green: GPIO4 # Moved to GPIO4
esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "resentment-industries.home-assistant-glow"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://resentment-industries/home-assistant-glow/home-assistant-glow/esp32.yaml@main

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  remote_package:
    url: https://github.com/resentment-industries/home-assistant-glow/
    ref: main  # Always pull latest from main branch
    refresh: 5min  # Check for updates every 5 minutes
    files:
      - components/basis.yaml
      - components/updates.yaml
      - components/status_led.yaml
      - components/pulse_meter.yaml

# Enable logging
logger:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # WiFi credentials
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Static IP to prevent mDNS issues
  manual_ip:
    static_ip: 192.168.1.209  # Change to match your network
    gateway: 192.168.1.1      # Your router IP
    subnet: 255.255.255.0

# Local Web Server running on port 80
web_server:
  id: esphome_web_server
  version: 3

time:
  - platform: sntp
    id: sntp_time

# Active-low sensor configuration with pullup (3.3V idle, 0.1V when light detected)
sensor:
  - id: !extend sensor_energy_pulse_meter1
    pin:
      number: ${pulse_pin1}
      mode:
        input: true
        pullup: true  # Prevents floating pin when sensor disconnected
      inverted: true  # Sensor goes low (0.1V) when detecting light
    timeout: 5min  # Add timeout for better accuracy
    internal_filter: 50ms
    filters:
      - filter_out: nan
      
  - id: !extend sensor_energy_pulse_meter2  
    pin:
      number: ${pulse_pin2}
      mode:
        input: true
        pullup: true  # Prevents floating pin when sensor disconnected
      inverted: true  # Sensor goes low (0.1V) when detecting light
    timeout: 5min  # Add timeout for better accuracy
    internal_filter: 50ms
    filters:
      - filter_out: nan